/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: GalaxyL (https://sketchfab.com/GalaxyL)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2281e7473c1745d88961ccb023c3e7d3
Title: 泡面模型
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Ramen(props) {
  const { nodes, materials } = useGLTF('/models/chips-transformed.glb')
  
  const modelRef = useRef();
  useFrame(() => {
    modelRef.current.rotation.y += 0.007;
  })
  return (
    <group {...props} dispose={null}
    scale={[1.25, 1.25, 1.25]}
    position={[0, 1, 0]}
    ref={modelRef}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chips_Chips001_0.geometry}
        material={materials['Chips.001']}
        position={[0, 0, 0.001]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/chips-transformed.glb')

