/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Xander Morningstar (https://sketchfab.com/XMorningstar)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/umbrella-4754f1bc1d6341d19b313ad6a51417de
Title: Umbrella
*/
"use client"
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

export default function Umbrella(props) {
  const { nodes, materials } = useGLTF('/models/umbrella-transformed.glb')

  const modelRef = useRef();

  useFrame((state, delta, xrFrame) => {
    if (modelRef.current) {
        modelRef.current.position.y = -3.5 + Math.sin(state.clock.elapsedTime) * 0.15;
      }
    })
  
  return (
    <group {...props} dispose={null} 
    ref={modelRef}
    position={[0, -3.5, 0]}
    scale={[0.6, 0.6, 0.6]}
    rotation={[0.1, 0, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.initialShadingGroup}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/umbrella-transformed.glb')
