/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Tanuki (https://sketchfab.com/tanukiart)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pocari-sweat-bottle-7c46341c63f0495c89d6871429dad261
Title: Pocari Sweat Bottle - ポカリ・スエット
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Yakult(props) {
  const { nodes, materials } = useGLTF('/models/yakult-transformed.glb')

  const modelRef = useRef();
  useFrame(() => {
    modelRef.current.rotation.y += 0.007;
  })
  return (
    <group {...props} dispose={null} ref={modelRef}
    scale={[45, 45, 45]}
    rotation={[0.4, -1, 0]}
    position={[0, 1.35, 0]}
    >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Yakult_Bottle_0.geometry}
          material={materials.Bottle}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.895, 0.895, 1.815]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Yakult001_Cap_0.geometry}
          material={materials.material}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.895, 0.895, 1.815]}
        />
      </group>
  );
}
useGLTF.preload('/models/yakult-transformed.glb')
